targetScope = 'subscription'

@description('Application name used for resource naming.')
param appName string

@description('Deployment environment name.')
param environmentName string

@description('Azure region for all resources.')
param location string

@description('Tags applied to provisioned resources.')
param tags object = {}

@description('Optional explicit resource group name. When empty, a name is generated.')
param resourceGroupName string = ''

@description('Tenant ID used by the frontend and API applications.')
param tenantId string = ''

@description('Frontend Entra app client ID.')
param frontendClientId string = ''

@secure()
@description('Frontend Entra app client secret.')
param frontendClientSecret string = ''

@description('API Entra app client ID.')
param apiClientId string = ''

@description('Dedicated single-tenant public launcher application client ID. Never the AVD managed identity.')
param brokerLauncherClientId string

@description('Enable only after the secured stack and reviewed migration have passed the cutover pilot. False pauses checkout, not authorization.')
param brokerCheckoutEnabled bool = false

@minLength(1)
@maxLength(128)
@description('Unique upcoming secured image tag. Provisioning must never start an older mutable latest image before post-provision builds and activates the secured stack.')
param containerImageTag string

@description('Explicitly selected existing AVD user security groups, not VM managed-identity groups.')
param workspaceUserGroupIds array = []

@description('Explicitly selected existing AVD users (Entra object IDs).')
param workspaceUserIds array = []

@secure()
@description('Linux host SSH private key stored in Key Vault for broker-managed SSH access.')
param linuxHostSshPrivateKey string = ''

@description('SQL administrator login.')
param sqlAdminLogin string = 'brokeradmin'

@secure()
@description('SQL administrator password.')
param sqlAdminPassword string = ''

@description('Dedicated contained API database user assigned only BrokerApiRuntime, never the SQL deployment administrator.')
param sqlRuntimeLogin string = 'brokerapi'

@secure()
@description('Separate password for the contained API runtime user; stored in the db-password Key Vault secret.')
param sqlRuntimePassword string

@secure()
@description('Flask session key for the frontend app.')
param flaskKey string = ''

@description('Optional custom domain used by Linux hosts.')
param domainName string = ''

@description('Optional NFS share used by Linux hosts.')
param nfsShare string = ''

@description('Admin login name used for Linux host provisioning.')
param linuxHostAdminLoginName string = 'avdadmin'

@secure()
@description('Admin password used for Linux and AVD host provisioning.')
param hostAdminPassword string = ''

@description('Optional resource group that contains managed VMs. Defaults to the deployment resource group.')
param vmHostResourceGroup string = ''

@description('Subscription ID that contains managed VMs. Defaults to the current subscription.')
param vmSubscriptionId string = subscription().subscriptionId

@description('Azure cloud the deployment targets. AzureCustom requires every custom endpoint parameter to be supplied.')
@allowed([
  'AzurePublic'
  'AzureUSGovernment'
  'AzureCustom'
])
param azureCloudName string = 'AzurePublic'

@description('Entra authority host. Leave empty to use the built-in value for the selected cloud.')
param azureAuthorityHost string = ''

@description('Microsoft Graph endpoint. Leave empty to use the built-in value for the selected cloud.')
param graphEndpoint string = ''

@description('Legacy STS issuer host used to validate v1 tokens. Leave empty to use the built-in value for the selected cloud.')
param stsIssuerHost string = ''

@description('App Service public hostname suffix. Leave empty to use the built-in value for the selected cloud.')
param appServiceDomain string = ''

@description('Root URL the Linux host bootstrap scripts are downloaded from. Point this at a reachable mirror for sovereign or air-gapped clouds.')
param scriptSourceRoot string = 'https://raw.githubusercontent.com/microsoft/LinuxBrokerForAVDAccess/refs/heads/main'

@description('SHA256 map for the exact LF/UTF-8 bootstrap and Linux helper sources, generated by preprovision. Required when deploying Linux hosts; mismatched downloads cannot execute.')
param linuxAgentFileHashes object = {}

@description('Locked private CPython runtime for all broker Linux hosts. Override only its URI with an approved byte-identical HTTPS mirror.')
param linuxPythonRuntime object = loadJsonContent('../linux-python.lock.json')

@description('Optional IPv4 address allowed through the SQL firewall.')
param allowedClientIp string = ''

@description('App Service plan SKU name.')
param appServicePlanSku string = 'P2mv3'

@description('Deploy Linux broker host VMs.')
param deployLinuxHosts bool = false

@description('Deploy Azure Virtual Desktop session hosts.')
param deployAvdHosts bool = false

@description('Linux host VM name prefix.')
param linuxHostVmNamePrefix string = 'lnxhost'

@description('Linux host VM size.')
param linuxHostVmSize string = 'Standard_D2s_v5'

@description('Number of Linux host VMs to deploy.')
param linuxHostCount int = 0

@allowed([
  'Password'
  'SSH'
])
@description('Authentication mode for Linux host VMs.')
param linuxHostAuthType string = 'SSH'

@description('SSH public key used when Linux host auth type is SSH.')
param linuxHostSshPublicKey string = ''

@allowed([
  '7-LVM'
  '8-LVM'
  '9-LVM'
  '24_04-lts'
])
@description('Linux host image SKU. The selected image must pass the verified XRDP reconnect-gate preflight; no lifecycle weakening or automatic OS upgrade is permitted.')
param linuxHostOsVersion string = '24_04-lts'

@description('Disable the GNOME screen saver and screen lock on RHEL hosts. Enabled by default because a locked greeter inside an xrdp/xpra session often cannot be unlocked after a reconnect, which strands the host lease. Set to false to keep the lock screen, for example to satisfy a STIG or CIS idle-lock control. Has no effect on the Ubuntu server image, which has no desktop.')
param linuxHostDisableScreenLock bool = true

@description('AVD host pool name.')
param avdHostPoolName string = ''

@description('Number of AVD session hosts to deploy.')
param avdSessionHostCount int = 0

@description('Maximum number of sessions per AVD session host.')
param avdMaxSessionLimit int = 5

@description('AVD session host VM name prefix.')
param avdVmNamePrefix string = 'avdhost'

@allowed([
  'Standard_DS2_v2'
  'Standard_D8s_v5'
  'Standard_D8s_v4'
  'Standard_F8s_v2'
  'Standard_D8as_v4'
  'Standard_D16s_v5'
  'Standard_D16s_v4'
  'Standard_F16s_v2'
  'Standard_D16as_v4'
])
@description('AVD session host VM size.')
param avdVmSize string = 'Standard_D8s_v5'

@description('Resource group used for deployment.')
var effectiveResourceGroupName = empty(resourceGroupName) ? 'rg-${appName}-${environmentName}' : resourceGroupName

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: effectiveResourceGroupName
  location: location
  tags: tags
}

module resources 'main.resources.bicep' = {
  name: 'resources'
  scope: rg
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
    tenantId: tenantId
    frontendClientId: frontendClientId
    frontendClientSecret: frontendClientSecret
    apiClientId: apiClientId
    brokerLauncherClientId: brokerLauncherClientId
    brokerCheckoutEnabled: brokerCheckoutEnabled
    containerImageTag: containerImageTag
    workspaceUserGroupIds: workspaceUserGroupIds
    workspaceUserIds: workspaceUserIds
    linuxHostSshPrivateKey: linuxHostSshPrivateKey
    sqlAdminLogin: sqlAdminLogin
    sqlAdminPassword: sqlAdminPassword
    sqlRuntimeLogin: sqlRuntimeLogin
    sqlRuntimePassword: sqlRuntimePassword
    flaskKey: flaskKey
    domainName: domainName
    nfsShare: nfsShare
    linuxHostAdminLoginName: linuxHostAdminLoginName
    hostAdminPassword: hostAdminPassword
    vmHostResourceGroup: vmHostResourceGroup
    vmSubscriptionId: vmSubscriptionId
    azureCloudName: azureCloudName
    azureAuthorityHost: azureAuthorityHost
    graphEndpoint: graphEndpoint
    stsIssuerHost: stsIssuerHost
    appServiceDomain: appServiceDomain
    scriptSourceRoot: scriptSourceRoot
    linuxAgentFileHashes: linuxAgentFileHashes
    linuxPythonRuntime: linuxPythonRuntime
    allowedClientIp: allowedClientIp
    appServicePlanSku: appServicePlanSku
    deployLinuxHosts: deployLinuxHosts
    deployAvdHosts: deployAvdHosts
    linuxHostVmNamePrefix: linuxHostVmNamePrefix
    linuxHostVmSize: linuxHostVmSize
    linuxHostCount: linuxHostCount
    linuxHostAuthType: linuxHostAuthType
    linuxHostSshPublicKey: linuxHostSshPublicKey
    linuxHostOsVersion: linuxHostOsVersion
    linuxHostDisableScreenLock: linuxHostDisableScreenLock
    avdHostPoolName: avdHostPoolName
    avdSessionHostCount: avdSessionHostCount
    avdMaxSessionLimit: avdMaxSessionLimit
    avdVmNamePrefix: avdVmNamePrefix
    avdVmSize: avdVmSize
  }
}

output resourceGroupName string = rg.name
output frontendAppName string = resources.outputs.frontendAppName
output frontendUrl string = resources.outputs.frontendUrl
output apiAppName string = resources.outputs.apiAppName
output apiUrl string = resources.outputs.apiUrl
output taskAppName string = resources.outputs.taskAppName
output keyVaultName string = resources.outputs.keyVaultName
output containerRegistryName string = resources.outputs.containerRegistryName
output sqlServerName string = resources.outputs.sqlServerName
output sqlDatabaseName string = resources.outputs.sqlDatabaseName
output virtualNetworkName string = resources.outputs.virtualNetworkName
output storageAccountName string = resources.outputs.storageAccountName
output storageBlobEndpoint string = resources.outputs.storageBlobEndpoint
output launcherArtifactContainerName string = resources.outputs.launcherArtifactContainerName
output avdApplicationGroupId string = resources.outputs.avdApplicationGroupId
output resolvedAuthorityHost string = resources.outputs.resolvedAuthorityHost
