#!/bin/bash

# Shared RHEL/Ubuntu agent. SQL owns expiry; this agent only reports verified observations.

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
umask 077

LOG_FILE="/var/log/release-session.log"
LOCATION_PATH="/usr/local/bin"
MANAGE_LEASE_SCRIPT="$LOCATION_PATH/manage-lease.sh"
BROKER_PYTHON="/usr/local/libexec/linuxbroker/python3"
APPLY_SETTINGS_SCRIPT="$LOCATION_PATH/apply-host-settings.sh"
SETTINGS_FILE="/etc/linuxbroker/host-settings.conf"
STATE_DIRECTORY="/var/lib/linuxbroker-release-session"
IDLE_WARNED_USERS_FILE="$STATE_DIRECTORY/idle_warned_users.tsv"
ACKED_VERSION_FILE="$STATE_DIRECTORY/acked_settings_version"
LOCK_FILE="$STATE_DIRECTORY/reconcile.lock"
hostname=$(hostname)
LOCK_FD=""

# Defaults matching the seeded profile in
# sql_queries/028_create_table-linux_host_settings.sql. They apply only until the first
# successful settings fetch, so a host that has never reached the broker behaves exactly as
# it did before these settings became configurable.
GRACE_PERIOD_SECONDS=1200
IDLE_TIMEOUT_SECONDS=0
IDLE_WARNING_SECONDS=120
SETTINGS_VERSION=0

RUN_MODE="manual"

for arg in "$@"; do
    case "$arg" in
        --systemd-timer)
            RUN_MODE="systemd-timer"
            ;;
        --logind-watcher)
            RUN_MODE="logind-watcher"
            ;;
        --cron)
            RUN_MODE="cron"
            ;;
    esac
done

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - [$RUN_MODE] - $1" | tee -a "$LOG_FILE"
}

ensure_state_files() {
    mkdir -p "$STATE_DIRECTORY"
    touch "$LOG_FILE" "$IDLE_WARNED_USERS_FILE"
    chmod 600 "$LOG_FILE" "$IDLE_WARNED_USERS_FILE"
}

acquire_reconcile_lock() {
    mkdir -p "$STATE_DIRECTORY"
    exec {LOCK_FD}> "$LOCK_FILE"

    if ! flock -n "$LOCK_FD"; then
        log "Another reconciliation run is already in progress. Skipping this invocation."
        eval "exec ${LOCK_FD}>&-"
        LOCK_FD=""
        exit 0
    fi
}

release_reconcile_lock() {
    if [ -n "$LOCK_FD" ]; then
        flock -u "$LOCK_FD" 2>/dev/null || true
        eval "exec ${LOCK_FD}>&-"
        LOCK_FD=""
    fi
}

# These files deduplicate idle warnings only; they never determine cleanup eligibility.
tsv_get() {
    local file="$1"
    local username="$2"

    [ -f "$file" ] || return 0

    awk -F '\t' -v user="$username" '$1 == user {print $2; exit}' "$file"
}

tsv_upsert() {
    local file="$1"
    local username="$2"
    local value="$3"
    local tmp_file

    touch "$file"
    tmp_file=$(mktemp)
    awk -F '\t' -v user="$username" '$1 != user' "$file" > "$tmp_file"
    printf '%s\t%s\n' "$username" "$value" >> "$tmp_file"
    mv "$tmp_file" "$file"
    chmod 600 "$file"
}

tsv_clear() {
    local file="$1"
    local username="$2"
    local tmp_file

    [ -f "$file" ] || return 0

    tmp_file=$(mktemp)
    awk -F '\t' -v user="$username" '$1 != user' "$file" > "$tmp_file"
    mv "$tmp_file" "$file"
    chmod 600 "$file"
}

# Reads the cached settings profile written by apply-host-settings.sh. The file only ever
# contains integers and booleans generated by that script, so sourcing it is safe.
load_settings() {
    if [ ! -r "$SETTINGS_FILE" ]; then
        return 0
    fi

    . "$SETTINGS_FILE"

    GRACE_PERIOD_SECONDS="${LINUXBROKER_GRACE_PERIOD_SECONDS:-$GRACE_PERIOD_SECONDS}"
    IDLE_TIMEOUT_SECONDS="${LINUXBROKER_IDLE_TIMEOUT_SECONDS:-$IDLE_TIMEOUT_SECONDS}"
    IDLE_WARNING_SECONDS="${LINUXBROKER_IDLE_WARNING_SECONDS:-$IDLE_WARNING_SECONDS}"
    SETTINGS_VERSION="${LINUXBROKER_SETTINGS_VERSION:-$SETTINGS_VERSION}"
}

# Cached settings can still control idle warnings; only the SQL policy authorizes expiry.
refresh_settings() {
    local api_base_url="$LINUXBROKER_API_BASE_URL"
    local settings_url="$api_base_url/hosts/settings"
    local ack_url="$api_base_url/hosts/$hostname/settings/ack"
    local access_token
    local response_file
    local http_status
    local fetched_version

    # Settings are only refreshed from the timer path. A watcher-mode run is a child of the
    # watcher service, and applying settings can restart that unit, which would SIGTERM this
    # process part-way through a reconcile. The timer path applies the change within one
    # interval anyway, so nothing is lost by skipping it here.
    if [ "$RUN_MODE" = "logind-watcher" ]; then
        return 0
    fi

    if [ ! -x "$APPLY_SETTINGS_SCRIPT" ]; then
        log "Settings apply script $APPLY_SETTINGS_SCRIPT is unavailable. Continuing with cached settings."
        return 0
    fi

    if ! access_token=$(get_access_token); then
        log "Unable to obtain an access token for the settings fetch. Continuing with cached settings."
        return 0
    fi

    response_file=$(mktemp)

    http_status=$(request_api GET "$settings_url" "$access_token" "" "$response_file")

    if ! [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        log "Settings fetch returned HTTP $http_status. Continuing with cached settings."
        rm -f "$response_file"
        return 0
    fi

    fetched_version=$(/usr/bin/jq -r '.SettingsVersion // empty' "$response_file" 2>/dev/null)

    if ! [[ "$fetched_version" =~ ^[0-9]+$ ]]; then
        log "Settings response did not contain a usable SettingsVersion. Continuing with cached settings."
        rm -f "$response_file"
        return 0
    fi

    if [ "$fetched_version" = "$SETTINGS_VERSION" ]; then
        # Already applied. The acknowledgement is tracked separately because it happens after
        # the version is written to disk; without this retry a single failed ack would leave
        # the host reported as drifted forever even though it is fully converged.
        if [ "$(read_acked_version)" != "$fetched_version" ]; then
            acknowledge_settings "$ack_url" "$access_token" "$fetched_version"
        fi

        rm -f "$response_file"
        return 0
    fi

    log "Applying settings version $fetched_version (was $SETTINGS_VERSION)."

    if "$APPLY_SETTINGS_SCRIPT" < "$response_file" >> "$LOG_FILE" 2>&1; then
        load_settings
        acknowledge_settings "$ack_url" "$access_token" "$fetched_version"
    else
        log "ERROR: Failed to apply settings version $fetched_version. Continuing with cached settings."
    fi

    rm -f "$response_file"
}

read_acked_version() {
    if [ -s "$ACKED_VERSION_FILE" ]; then
        tr -d '\r\n' < "$ACKED_VERSION_FILE"
    fi
}

acknowledge_settings() {
    local ack_url="$1"
    local access_token="$2"
    local applied_version="$3"
    local http_status

    http_status=$(request_api POST "$ack_url" "$access_token" \
        "$(/usr/bin/jq -cn --argjson settingsVersion "$applied_version" '{settingsVersion: $settingsVersion}')" /dev/null)

    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        # Recorded only on success, so a failed acknowledgement is retried on the next run.
        printf '%s\n' "$applied_version" > "$ACKED_VERSION_FILE"
        chmod 600 "$ACKED_VERSION_FILE"
        log "Acknowledged settings version $applied_version."
    else
        log "Could not acknowledge settings version $applied_version (HTTP $http_status)."
    fi
}

get_access_token() {
    local resource="api://$LINUXBROKER_API_CLIENT_ID"
    local imds_endpoint="http://169.254.169.254/metadata/identity/oauth2/token"
    local api_version="2018-02-01"
    local uri="$imds_endpoint?api-version=$api_version&resource=$resource"

    local headers="Metadata:true"
    local access_token
    access_token=$(/usr/bin/curl -fsS -m 10 --header "$headers" "$uri" | /usr/bin/jq -er '.access_token')

    if [ "$access_token" == "null" ] || ! [[ "$access_token" =~ ^[A-Za-z0-9._-]+$ ]]; then
        log "ERROR: Failed to obtain access token." >&2
        return 1
    fi

    echo "$access_token"
}

request_api() {
    local method="$1" url="$2" token="$3" body="$4" output="$5"
    # curl reads the bearer header from stdin, not argv or a token file.
    printf 'header = "Authorization: Bearer %s"\n' "$token" |
        /usr/bin/curl --config - -sS -m 150 -w "%{http_code}" -o "$output" -X "$method" "$url" \
            -H "Content-Type: application/json" --data "$body"
}

report_session() {
    local observation="$1" access_token request_body http_status
    if ! request_body=$(printf '%s' "$observation" | /usr/bin/jq -ce '
        select(.leaseId | type == "string") |
        select(.leaseGeneration | type == "number") |
        select(.leaseGeneration > 0 and .leaseGeneration <= 9007199254740991 and .leaseGeneration == (.leaseGeneration | floor)) |
        select(.state == "active" or .state == "disconnected" or .state == "logged_off") |
        {leaseId, leaseGeneration, state}'); then
        log "ERROR: The root lease helper returned an invalid observation."
        return 1
    fi
    if ! access_token=$(get_access_token); then
        return 1
    fi
    http_status=$(request_api POST "$LINUXBROKER_API_BASE_URL/vms/$hostname/session" "$access_token" "$request_body" /dev/null)
    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        return 0
    fi
    log "Session observation was not accepted (HTTP $http_status); retrying from a fresh marker next run."
    return 1
}

# ---------------------------------------------------------------------------
# Idle session enforcement
#
# Disabled when IDLE_TIMEOUT_SECONDS is 0, which is the shipped default.
#
# Enforcement deliberately fails open. If idle time cannot be read for any reason the user
# is left alone, because wrongly disconnecting an active user is far worse than letting an
# idle one hold a VM for another poll.
# ---------------------------------------------------------------------------

get_session_display() {
    local xorg_pid="$1"

    tr '\0' '\n' < "/proc/$xorg_pid/cmdline" 2>/dev/null | grep -m1 -E '^:[0-9]+$'
}

get_session_xauthority() {
    local xorg_pid="$1"
    local auth_path
    local xorg_cwd

    auth_path=$(tr '\0' '\n' < "/proc/$xorg_pid/cmdline" 2>/dev/null | awk '$0 == "-auth" { getline; print; exit }')

    if [ -z "$auth_path" ]; then
        return 0
    fi

    # xrdp 0.9.x passes a bare ".Xauthority", which is only meaningful relative to the Xorg
    # process's working directory (the session owner's home). This agent runs with its own
    # WorkingDirectory, so the path has to be resolved here or every idle lookup would fail
    # to open the display and idle enforcement would silently never fire.
    if [ "${auth_path#/}" = "$auth_path" ]; then
        xorg_cwd=$(readlink -f "/proc/$xorg_pid/cwd" 2>/dev/null)

        if [ -n "$xorg_cwd" ]; then
            auth_path="$xorg_cwd/$auth_path"
        fi
    fi

    echo "$auth_path"
}

get_session_idle_seconds() {
    local xorg_pid="$1"
    local display
    local xauthority
    local idle_milliseconds

    if ! command -v xprintidle >/dev/null 2>&1; then
        return 1
    fi

    display=$(get_session_display "$xorg_pid")
    if [ -z "$display" ]; then
        return 1
    fi

    xauthority=$(get_session_xauthority "$xorg_pid")

    if [ -n "$xauthority" ]; then
        idle_milliseconds=$(DISPLAY="$display" XAUTHORITY="$xauthority" xprintidle 2>/dev/null)
    else
        idle_milliseconds=$(DISPLAY="$display" xprintidle 2>/dev/null)
    fi

    if ! [[ "$idle_milliseconds" =~ ^[0-9]+$ ]]; then
        return 1
    fi

    echo $((idle_milliseconds / 1000))
}

warn_idle_user() {
    local username="$1"
    local xorg_pid="$2"
    local remaining="$3"
    local display
    local xauthority
    local user_id
    local message="Your session has been idle and will be disconnected in $remaining seconds. Move the mouse or press a key to stay connected."

    display=$(get_session_display "$xorg_pid")
    [ -z "$display" ] && return 1

    xauthority=$(get_session_xauthority "$xorg_pid")
    user_id=$(id -u "$username" 2>/dev/null)

    if command -v notify-send >/dev/null 2>&1 && [ -n "$user_id" ] && command -v runuser >/dev/null 2>&1; then
        if DISPLAY="$display" XAUTHORITY="$xauthority" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
            runuser -u "$username" -- notify-send "Idle session warning" "$message" >/dev/null 2>&1; then
            return 0
        fi
    fi

    if command -v xmessage >/dev/null 2>&1; then
        DISPLAY="$display" XAUTHORITY="$xauthority" xmessage -timeout 30 "$message" >/dev/null 2>&1 &
        return 0
    fi

    return 1
}

disconnect_session() {
    local username="$1" xorg_pid="$2" observation="$3" uid lease generation
    uid=$(printf '%s' "$observation" | /usr/bin/jq -r '.uid')
    lease=$(printf '%s' "$observation" | /usr/bin/jq -r '.leaseId')
    generation=$(printf '%s' "$observation" | /usr/bin/jq -r '.leaseGeneration')
    if ! "$MANAGE_LEASE_SCRIPT" disconnect-idle "$username" "$uid" "$lease" "$generation" "$xorg_pid" >/dev/null; then
        log "The lease changed or the idle connection could not be verified; no unguarded disconnect is permitted."
        return 1
    fi
    return 0
}

enforce_idle_session() {
    local username="$1"
    local xorg_pid="$2"
    local observation="$3"
    local idle_seconds
    local warn_threshold
    local already_warned

    if [ "$IDLE_TIMEOUT_SECONDS" -le 0 ]; then
        return 0
    fi

    if ! idle_seconds=$(get_session_idle_seconds "$xorg_pid"); then
        log "Could not read idle time for user $username. Skipping idle enforcement."
        return 0
    fi

    if [ "$idle_seconds" -ge "$IDLE_TIMEOUT_SECONDS" ]; then
        log "User $username has been idle for $idle_seconds seconds. Disconnecting the session."

        if disconnect_session "$username" "$xorg_pid" "$observation"; then
            tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
        fi

        return 0
    fi

    if [ "$IDLE_WARNING_SECONDS" -le 0 ]; then
        return 0
    fi

    warn_threshold=$((IDLE_TIMEOUT_SECONDS - IDLE_WARNING_SECONDS))

    if [ "$idle_seconds" -lt "$warn_threshold" ]; then
        # The user is active again, so clear the marker and let a fresh warning be sent if
        # they go idle later. Clearing it any earlier would defeat the dedup check below and
        # re-warn on every single run for the whole warning window.
        tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
        return 0
    fi

    already_warned=$(tsv_get "$IDLE_WARNED_USERS_FILE" "$username")
    if [ -n "$already_warned" ]; then
        return 0
    fi

    if warn_idle_user "$username" "$xorg_pid" "$((IDLE_TIMEOUT_SECONDS - idle_seconds))"; then
        tsv_upsert "$IDLE_WARNED_USERS_FILE" "$username" "$(date +%s)"
        log "Warned user $username that the session is approaching the idle limit."
    fi
}

main() {
    local observation result username status pid
    if [[ "${LINUXBROKER_API_BASE_URL:-}" != https://* ]] || [ -z "${LINUXBROKER_API_CLIENT_ID:-}" ]; then
        log "ERROR: A configured HTTPS broker URL and API client ID are required."
        return 1
    fi
    if ! command -v jq >/dev/null || [ ! -f "$BROKER_PYTHON" ] || [ ! -x "$BROKER_PYTHON" ]; then
        log "ERROR: jq and the deployment-pinned Python 3.9+ runtime must be installed by provisioning."
        return 1
    fi
    ensure_state_files
    load_settings
    refresh_settings
    observation=$("$MANAGE_LEASE_SCRIPT" observe)
    result=$?
    if [ "$result" -eq 3 ]; then
        log "No live broker lease."
        return 0
    elif [ "$result" -ne 0 ]; then
        log "ERROR: Lease state is uncertain; no local cleanup is permitted."
        return 1
    fi
    if ! report_session "$observation"; then
        return 1
    fi
    username=$(printf '%s' "$observation" | /usr/bin/jq -r '.username')
    status=$(printf '%s' "$observation" | /usr/bin/jq -r '.state')
    pid=$(printf '%s' "$observation" | /usr/bin/jq -r '.xorgPid // empty')
    if [ "$status" = "active" ] && [[ "$pid" =~ ^[0-9]+$ ]]; then
        enforce_idle_session "$username" "$pid" "$observation"
    else
        tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
    fi
    log "Script completed."
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [ "$EUID" -ne 0 ]; then
        echo "Session reconciliation requires root." >&2
        exit 1
    fi
    acquire_reconcile_lock
    log "Script started."
    trap "release_reconcile_lock; log 'Script exiting.'" EXIT
    main
fi
