#!/bin/bash

# Support for RHEL systems

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# The Linux Broker host agent version. Every script in linux_host/ declares the same value
# and the heartbeat reports it; bump them together with HOST_AGENT_VERSION in api/config.py.
LINUXBROKER_AGENT_VERSION="1.1.0"

LOG_FILE="/var/log/release-session.log"
LOCATION_PATH="/usr/local/bin"
XORG_USERS_INFO_SCRIPT="$LOCATION_PATH/xrdp-who-xorg.sh"
APPLY_SETTINGS_SCRIPT="$LOCATION_PATH/apply-host-settings.sh"
SETTINGS_FILE="/etc/linuxbroker/host-settings.conf"
STATE_DIRECTORY="/var/lib/linuxbroker-release-session"
LEASE_DIRECTORY="$STATE_DIRECTORY/leases"
CURRENT_USERS_DETAILS="$STATE_DIRECTORY/current_users.txt"
PREVIOUS_USERS_FILE="$STATE_DIRECTORY/previous_users.txt"
DISCONNECTED_USERS_FILE="$STATE_DIRECTORY/disconnected_users.tsv"
IDLE_WARNED_USERS_FILE="$STATE_DIRECTORY/idle_warned_users.tsv"
ACKED_VERSION_FILE="$STATE_DIRECTORY/acked_settings_version"
LOCK_FILE="$STATE_DIRECTORY/reconcile.lock"
hostname=$(hostname)
LOCK_FD=""

# Defaults matching the seeded profile in
# sql_queries/028_create_table-linux_host_settings.sql. They apply only until the first
# successful settings fetch, so a host that has never reached the broker behaves exactly as
# it did before these settings became configurable.
GRACE_PERIOD_SECONDS=1200
IDLE_TIMEOUT_SECONDS=0
IDLE_WARNING_SECONDS=120
SETTINGS_VERSION=0
PRESERVE_SESSIONS_ON_DISCONNECT=false

RUN_MODE="manual"

for arg in "$@"; do
    case "$arg" in
        --systemd-timer)
            RUN_MODE="systemd-timer"
            ;;
        --logind-watcher)
            RUN_MODE="logind-watcher"
            ;;
        --cron)
            RUN_MODE="cron"
            ;;
    esac
done

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - [$RUN_MODE] - $1" | tee -a "$LOG_FILE"
}

ensure_state_files() {
    mkdir -p "$STATE_DIRECTORY"
    # Temporary files are written here so the final mv is an atomic rename, and API
    # responses and lease state must not be readable by the users signed in to the host.
    chmod 700 "$STATE_DIRECTORY"
    touch "$LOG_FILE" "$CURRENT_USERS_DETAILS" "$PREVIOUS_USERS_FILE" "$DISCONNECTED_USERS_FILE" "$IDLE_WARNED_USERS_FILE"
    chmod 600 "$LOG_FILE" "$CURRENT_USERS_DETAILS" "$PREVIOUS_USERS_FILE" "$DISCONNECTED_USERS_FILE" "$IDLE_WARNED_USERS_FILE"
}

acquire_reconcile_lock() {
    mkdir -p "$STATE_DIRECTORY"
    exec {LOCK_FD}> "$LOCK_FILE"

    if ! flock -n "$LOCK_FD"; then
        log "Another reconciliation run is already in progress. Skipping this invocation."
        eval "exec ${LOCK_FD}>&-"
        LOCK_FD=""
        exit 0
    fi
}

release_reconcile_lock() {
    if [ -n "$LOCK_FD" ]; then
        flock -u "$LOCK_FD" 2>/dev/null || true
        eval "exec ${LOCK_FD}>&-"
        LOCK_FD=""
    fi
}

resolve_xrdp_users_info_script() {
    if [ -x "$XORG_USERS_INFO_SCRIPT" ]; then
        echo "$XORG_USERS_INFO_SCRIPT"
        return 0
    fi

    return 1
}

array_contains() {
    local needle="$1"
    shift
    local item

    for item in "$@"; do
        if [ "$item" = "$needle" ]; then
            return 0
        fi
    done

    return 1
}

get_disconnect_timestamp() {
    tsv_get "$DISCONNECTED_USERS_FILE" "$1"
}

upsert_disconnect_timestamp() {
    tsv_upsert "$DISCONNECTED_USERS_FILE" "$1" "$2"
}

clear_disconnect_timestamp() {
    tsv_clear "$DISCONNECTED_USERS_FILE" "$1"
}

# Generic single-key-per-user TSV helpers, shared by the disconnect and idle-warning state
# files so both behave identically.
tsv_get() {
    local file="$1"
    local username="$2"

    [ -f "$file" ] || return 0

    awk -F '\t' -v user="$username" '$1 == user {print $2; exit}' "$file"
}

tsv_upsert() {
    local file="$1"
    local username="$2"
    local value="$3"
    local tmp_file

    touch "$file"
    tmp_file="$STATE_DIRECTORY/$(basename "$file").$$.tmp"
    awk -F '\t' -v user="$username" '$1 != user' "$file" > "$tmp_file"
    printf '%s\t%s\n' "$username" "$value" >> "$tmp_file"
    mv "$tmp_file" "$file"
    chmod 600 "$file"
}

tsv_clear() {
    local file="$1"
    local username="$2"
    local tmp_file

    [ -f "$file" ] || return 0

    tmp_file="$STATE_DIRECTORY/$(basename "$file").$$.tmp"
    awk -F '\t' -v user="$username" '$1 != user' "$file" > "$tmp_file"
    mv "$tmp_file" "$file"
    chmod 600 "$file"
}

# Reads the cached settings profile written by apply-host-settings.sh. The file only ever
# contains integers and booleans generated by that script, so sourcing it is safe.
load_settings() {
    if [ ! -r "$SETTINGS_FILE" ]; then
        return 0
    fi

    . "$SETTINGS_FILE"

    GRACE_PERIOD_SECONDS="${LINUXBROKER_GRACE_PERIOD_SECONDS:-$GRACE_PERIOD_SECONDS}"
    IDLE_TIMEOUT_SECONDS="${LINUXBROKER_IDLE_TIMEOUT_SECONDS:-$IDLE_TIMEOUT_SECONDS}"
    IDLE_WARNING_SECONDS="${LINUXBROKER_IDLE_WARNING_SECONDS:-$IDLE_WARNING_SECONDS}"
    SETTINGS_VERSION="${LINUXBROKER_SETTINGS_VERSION:-$SETTINGS_VERSION}"
    PRESERVE_SESSIONS_ON_DISCONNECT="${LINUXBROKER_PRESERVE_SESSIONS_ON_DISCONNECT:-$PRESERVE_SESSIONS_ON_DISCONNECT}"
}

# Pull side of settings delivery. Every failure path here is non-fatal: reconciliation is
# the job that actually reclaims VMs, so it must never be blocked by a settings problem.
refresh_settings() {
    local api_base_url="YOUR_LINUX_BROKER_API_BASE_URL"
    local settings_url="$api_base_url/hosts/settings"
    local ack_url="$api_base_url/hosts/$hostname/settings/ack"
    local access_token
    local response_file
    local http_status
    local fetched_version

    # Settings are only refreshed from the timer path. A watcher-mode run is a child of the
    # watcher service, and applying settings can restart that unit, which would SIGTERM this
    # process part-way through a reconcile. The timer path applies the change within one
    # interval anyway, so nothing is lost by skipping it here.
    if [ "$RUN_MODE" = "logind-watcher" ]; then
        return 0
    fi

    if [ ! -x "$APPLY_SETTINGS_SCRIPT" ]; then
        log "Settings apply script $APPLY_SETTINGS_SCRIPT is unavailable. Continuing with cached settings."
        return 0
    fi

    if ! access_token=$(get_access_token); then
        log "Unable to obtain an access token for the settings fetch. Continuing with cached settings."
        return 0
    fi

    response_file="$STATE_DIRECTORY/settings-response.$$.json"

    http_status=$(/usr/bin/curl -s -m 20 -w "%{http_code}" -o "$response_file" -X GET "$settings_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json")

    if ! [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        log "Settings fetch returned HTTP $http_status. Continuing with cached settings."
        rm -f "$response_file"
        return 0
    fi

    fetched_version=$(/usr/bin/jq -r '.SettingsVersion // empty' "$response_file" 2>/dev/null)

    if ! [[ "$fetched_version" =~ ^[0-9]+$ ]]; then
        log "Settings response did not contain a usable SettingsVersion. Continuing with cached settings."
        rm -f "$response_file"
        return 0
    fi

    if [ "$fetched_version" = "$SETTINGS_VERSION" ]; then
        # Already applied. The acknowledgement is tracked separately because it happens after
        # the version is written to disk; without this retry a single failed ack would leave
        # the host reported as drifted forever even though it is fully converged.
        if [ "$(read_acked_version)" != "$fetched_version" ]; then
            acknowledge_settings "$ack_url" "$access_token" "$fetched_version"
        fi

        rm -f "$response_file"
        return 0
    fi

    log "Applying settings version $fetched_version (was $SETTINGS_VERSION)."

    if "$APPLY_SETTINGS_SCRIPT" < "$response_file" >> "$LOG_FILE" 2>&1; then
        load_settings
        acknowledge_settings "$ack_url" "$access_token" "$fetched_version"
    else
        log "ERROR: Failed to apply settings version $fetched_version. Continuing with cached settings."
    fi

    rm -f "$response_file"
}

read_acked_version() {
    if [ -s "$ACKED_VERSION_FILE" ]; then
        tr -d '\r\n' < "$ACKED_VERSION_FILE"
    fi
}

acknowledge_settings() {
    local ack_url="$1"
    local access_token="$2"
    local applied_version="$3"
    local http_status

    http_status=$(/usr/bin/curl -s -m 20 -w "%{http_code}" -o /dev/null -X POST "$ack_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json" \
        -d "$(/usr/bin/jq -cn --argjson settingsVersion "$applied_version" '{settingsVersion: $settingsVersion}')")

    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        # Recorded only on success, so a failed acknowledgement is retried on the next run.
        printf '%s\n' "$applied_version" > "$ACKED_VERSION_FILE"
        chmod 600 "$ACKED_VERSION_FILE"
        log "Acknowledged settings version $applied_version."
    else
        log "Could not acknowledge settings version $applied_version (HTTP $http_status)."
    fi
}

xorg_processes_for_user() {
    local username="$1"

    ps h -C Xorg -o pid=,user=,comm= 2>/dev/null | awk -v user="$username" '$2 == user {print $1 ":" $3}'
}

xorg_processes_remaining() {
    local username="$1"

    [ -n "$(xorg_processes_for_user "$username")" ]
}

terminate_session_processes() {
    local username="$1"
    local found_process="false"

    while IFS=: read -r pid process_name; do
        [ -z "$pid" ] && continue

        found_process="true"
        log "$process_name PID for user $username: $pid"

        if kill -9 "$pid" 2>/dev/null; then
            log "Terminated $process_name process $pid for user $username."
        else
            log "ERROR: Failed to terminate $process_name process $pid for user $username."
        fi
    done < <(xorg_processes_for_user "$username")

    if [ "$found_process" != "true" ]; then
        log "No XRDP session process found for user $username."
    fi
}

get_access_token() {
    local resource="api://YOUR_LINUX_BROKER_API_CLIENT_ID"
    local imds_endpoint="http://169.254.169.254/metadata/identity/oauth2/token"
    local api_version="2018-02-01"
    local uri="$imds_endpoint?api-version=$api_version&resource=$resource"

    local headers="Metadata:true"
    local access_token=$(/usr/bin/curl -s -m 10 --header "$headers" "$uri" | /usr/bin/jq -r '.access_token')

    if [ "$access_token" == "null" ] || [ -z "$access_token" ]; then
        log "ERROR: Failed to obtain access token."
        # Returning rather than exiting lets non-critical callers such as the settings fetch
        # continue. release_vm still treats an empty token as fatal.
        return 1
    fi

    echo "$access_token"
}

get_current_lease_id() {
    local username="$1"
    local lease_file="$LEASE_DIRECTORY/$username.lease"

    if [ ! -f "$lease_file" ]; then
        return 1
    fi

    tr -d '\r\n' < "$lease_file"
}

release_vm() {
    local username="$1"
    local api_base_url="YOUR_LINUX_BROKER_API_BASE_URL"
    local release_vm_url="$api_base_url/vms/$hostname/release"
    local access_token
    local lease_id=""
    local request_body
    local response_file
    local http_status
    local json_hostname
    local json_lease_id
    local release_status
    local release_succeeded=1

    access_token=$(get_access_token)

    if [ -z "$access_token" ]; then
        log "ERROR: Unable to obtain access token."
        exit 1
    fi

    if lease_id=$(get_current_lease_id "$username"); then
        request_body=$(/usr/bin/jq -cn --arg username "$username" --arg leaseId "$lease_id" '{username: $username, leaseId: $leaseId}')
    else
        log "No lease marker found for user $username. Falling back to username-only release."
        request_body=$(/usr/bin/jq -cn --arg username "$username" '{username: $username}')
    fi

    response_file="$STATE_DIRECTORY/release-response.$$.json"

    http_status=$(/usr/bin/curl -s -w "%{http_code}" -o "$response_file" -X POST "$release_vm_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json" \
        -d "$request_body")

    json_hostname=$(/usr/bin/jq -r '.Hostname // empty' "$response_file" 2>/dev/null)
    json_lease_id=$(/usr/bin/jq -r '.LeaseId // empty' "$response_file" 2>/dev/null)
    release_status=$(/usr/bin/jq -r '.ReleaseStatus // empty' "$response_file" 2>/dev/null)

    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        if [ "$release_status" == "NoActiveAssignment" ]; then
            log "INFO: VM $hostname already has no active assignment. Nothing to release for user $username."
            release_succeeded=0
        elif [ "$json_hostname" != "$hostname" ]; then
            log "ERROR: Release response returned Hostname '$json_hostname' but expected '$hostname'."
        elif [ -n "$lease_id" ] && [ "$json_lease_id" != "$lease_id" ]; then
            log "ERROR: Release response for $hostname returned LeaseId '$json_lease_id' but expected '$lease_id'."
        else
            log "INFO: Successfully released VM with Hostname: $hostname"
            release_succeeded=0
        fi
    elif [ "$http_status" == "409" ]; then
        # The broker reassigned this host, so retrying cannot succeed.
        log "INFO: Lease for user $username on $hostname is stale. Skipping further release attempts."
        release_succeeded=0
    elif [ "$http_status" == "404" ]; then
        log "ERROR: The broker does not recognize Hostname $hostname. Skipping further release attempts."
        release_succeeded=0
    else
        log "ERROR: Failed to release VM with Hostname: $hostname (HTTP Status: $http_status)"
    fi

    cat "$response_file" >> "$LOG_FILE"

    if [ "$PRESERVE_SESSIONS_ON_DISCONNECT" != "true" ]; then
        terminate_session_processes "$username"
    else
        log "PreserveSessionsOnDisconnect is enabled. Leaving Xorg processes for user $username running after release."
    fi

    rm -f "$response_file"

    return "$release_succeeded"
}

terminate_logind_sessions() {
    local username="$1"
    local session_ids
    local session_id

    session_ids=$(loginctl list-sessions --no-legend 2>/dev/null | awk -v user="$username" '$3 == user {print $1}')

    if [ -z "$session_ids" ]; then
        log "No logind sessions found for user $username."
        return 0
    fi

    for session_id in $session_ids; do
        if loginctl terminate-session "$session_id"; then
            log "Logged off user $username session $session_id after grace period."
        else
            log "ERROR: Failed to log off user $username session $session_id."
        fi
    done
}

reconcile_disconnected_user() {
    local username="$1"
    local disconnected_at="$2"
    local now="$3"
    local elapsed=$((now - disconnected_at))
    local remaining

    if [ "$elapsed" -ge "$GRACE_PERIOD_SECONDS" ]; then
        log "User $username remained disconnected for $elapsed seconds. Terminating remaining sessions."
        terminate_logind_sessions "$username"
        terminate_session_processes "$username"

        if xorg_processes_remaining "$username"; then
            log "ERROR: Xorg processes remain for user $username after grace-period cleanup. Keeping disconnect timestamp for retry."
            return
        fi

        clear_disconnect_timestamp "$username"
        return
    fi

    remaining=$((GRACE_PERIOD_SECONDS - elapsed))
    log "User $username is still disconnected. Grace period expires in $remaining seconds."
}

# ---------------------------------------------------------------------------
# Idle session enforcement
#
# Disabled when IDLE_TIMEOUT_SECONDS is 0, which is the shipped default.
#
# Enforcement deliberately fails open. If idle time cannot be read for any reason the user
# is left alone, because wrongly disconnecting an active user is far worse than letting an
# idle one hold a VM for another poll.
# ---------------------------------------------------------------------------

# Reading a session's idle time goes through its X server and its owner's home, either of
# which can hang: a wedged Xorg, or a hard-mounted NFS home that is unreachable.
SESSION_PROBE_TIMEOUT_SECONDS=5

get_session_display() {
    local xorg_pid="$1"

    tr '\0' '\n' < "/proc/$xorg_pid/cmdline" 2>/dev/null | grep -m1 -E '^:[0-9]+$'
}

get_session_xauthority() {
    local xorg_pid="$1"
    local auth_path
    local xorg_cwd

    auth_path=$(tr '\0' '\n' < "/proc/$xorg_pid/cmdline" 2>/dev/null | awk '$0 == "-auth" { getline; print; exit }')

    if [ -z "$auth_path" ]; then
        return 0
    fi

    # xrdp 0.9.x passes a bare ".Xauthority", which is only meaningful relative to the Xorg
    # process's working directory (the session owner's home). This agent runs with its own
    # WorkingDirectory, so the path has to be resolved here or every idle lookup would fail
    # to open the display and idle enforcement would silently never fire.
    if [ "${auth_path#/}" = "$auth_path" ]; then
        # Resolving the path stats the user's home, which blocks while an NFS home is hung.
        xorg_cwd=$(timeout "$SESSION_PROBE_TIMEOUT_SECONDS" readlink -f "/proc/$xorg_pid/cwd" 2>/dev/null)

        if [ -n "$xorg_cwd" ]; then
            auth_path="$xorg_cwd/$auth_path"
        fi
    fi

    echo "$auth_path"
}

get_session_idle_seconds() {
    local xorg_pid="$1"
    local display
    local xauthority
    local idle_milliseconds

    if ! command -v xprintidle >/dev/null 2>&1; then
        return 1
    fi

    display=$(get_session_display "$xorg_pid")
    if [ -z "$display" ]; then
        return 1
    fi

    xauthority=$(get_session_xauthority "$xorg_pid")

    if [ -n "$xauthority" ]; then
        idle_milliseconds=$(DISPLAY="$display" XAUTHORITY="$xauthority" timeout "$SESSION_PROBE_TIMEOUT_SECONDS" xprintidle 2>/dev/null)
    else
        idle_milliseconds=$(DISPLAY="$display" timeout "$SESSION_PROBE_TIMEOUT_SECONDS" xprintidle 2>/dev/null)
    fi

    if ! [[ "$idle_milliseconds" =~ ^[0-9]+$ ]]; then
        return 1
    fi

    echo $((idle_milliseconds / 1000))
}

warn_idle_user() {
    local username="$1"
    local xorg_pid="$2"
    local remaining="$3"
    local display
    local xauthority
    local user_id
    local message="Your session has been idle and will be disconnected in $remaining seconds. Move the mouse or press a key to stay connected."

    display=$(get_session_display "$xorg_pid")
    [ -z "$display" ] && return 1

    xauthority=$(get_session_xauthority "$xorg_pid")
    user_id=$(id -u "$username" 2>/dev/null)

    if command -v notify-send >/dev/null 2>&1 && [ -n "$user_id" ] && command -v runuser >/dev/null 2>&1; then
        if DISPLAY="$display" XAUTHORITY="$xauthority" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
            runuser -u "$username" -- notify-send "Idle session warning" "$message" >/dev/null 2>&1; then
            return 0
        fi
    fi

    if command -v xmessage >/dev/null 2>&1; then
        DISPLAY="$display" XAUTHORITY="$xauthority" xmessage -timeout 30 "$message" >/dev/null 2>&1 &
        return 0
    fi

    return 1
}

# Drops the client connection while leaving Xorg running, so the session survives and the
# user can reconnect inside the grace period. Only processes named xrdp that hold the
# session's display socket are terminated, which is the same signal xrdp-who-xorg.sh uses to
# decide whether a session is connected.
disconnect_session() {
    local username="$1"
    local xorg_pid="$2"
    local display
    local display_number
    local pid
    local process_name
    local disconnected="false"

    display=$(get_session_display "$xorg_pid")
    if [ -z "$display" ]; then
        log "Could not determine the display for user $username. Skipping idle disconnect."
        return 1
    fi

    display_number="${display#:}"

    while read -r pid; do
        [ -z "$pid" ] && continue
        [ "$pid" = "$xorg_pid" ] && continue

        process_name=$(ps -p "$pid" -o comm= 2>/dev/null | xargs)
        if [ "$process_name" != "xrdp" ]; then
            continue
        fi

        if kill -TERM "$pid" 2>/dev/null; then
            disconnected="true"
            log "Disconnected idle xrdp connection $pid for user $username."
        else
            log "ERROR: Failed to disconnect xrdp connection $pid for user $username."
        fi
    done < <(
        ss -xp 2>/dev/null \
            | grep -E "xrdp_display_${display_number}([^0-9]|$)" \
            | grep -oE 'pid=[0-9]+' \
            | cut -d= -f2 \
            | sort -u
    )

    if [ "$disconnected" != "true" ]; then
        log "No xrdp connection process was found for user $username on display $display."
        return 1
    fi

    return 0
}

enforce_idle_session() {
    local username="$1"
    local xorg_pid="$2"
    local idle_seconds
    local warn_threshold
    local already_warned

    if [ "$IDLE_TIMEOUT_SECONDS" -le 0 ]; then
        return 0
    fi

    if ! idle_seconds=$(get_session_idle_seconds "$xorg_pid"); then
        log "Could not read idle time for user $username. Skipping idle enforcement."
        return 0
    fi

    if [ "$idle_seconds" -ge "$IDLE_TIMEOUT_SECONDS" ]; then
        log "User $username has been idle for $idle_seconds seconds. Disconnecting the session."

        if disconnect_session "$username" "$xorg_pid"; then
            tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
        fi

        return 0
    fi

    if [ "$IDLE_WARNING_SECONDS" -le 0 ]; then
        return 0
    fi

    warn_threshold=$((IDLE_TIMEOUT_SECONDS - IDLE_WARNING_SECONDS))

    if [ "$idle_seconds" -lt "$warn_threshold" ]; then
        # The user is active again, so clear the marker and let a fresh warning be sent if
        # they go idle later. Clearing it any earlier would defeat the dedup check below and
        # re-warn on every single run for the whole warning window.
        tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
        return 0
    fi

    already_warned=$(tsv_get "$IDLE_WARNED_USERS_FILE" "$username")
    if [ -n "$already_warned" ]; then
        return 0
    fi

    if warn_idle_user "$username" "$xorg_pid" "$((IDLE_TIMEOUT_SECONDS - idle_seconds))"; then
        tsv_upsert "$IDLE_WARNED_USERS_FILE" "$username" "$(date +%s)"
        log "Warned user $username that the session is approaching the idle limit."
    fi
}

check_unmount_user_homes() {
    local username

    log "Scanning for orphaned mounted user home directories."

    mapfile -t logged_in_users < <(loginctl list-users --no-legend 2>/dev/null | awk '{print $2}')

    while read -r device mountpoint fstype rest; do
        if [[ "$mountpoint" =~ ^/home/[^/]+$ ]]; then
            username=$(basename "$mountpoint")

            # The broker mounts the home at checkout, before the user signs in, and the SSH
            # login it uses wakes the logind watcher. Unmounting whenever the user is not
            # signed in would pull the profile out from under nearly every new session, so
            # the home stays mounted until the broker returns the host. manage-lease.sh
            # unmounts it then, before the account is deleted.
            if [ -f "$LEASE_DIRECTORY/$username.lease" ]; then
                log "User $username holds a lease on this host. Keeping $mountpoint mounted."
            elif ! array_contains "$username" "${logged_in_users[@]}"; then
                log "User $username is not logged in. Attempting to unmount $mountpoint"

                if umount -l "$mountpoint"; then
                    log "Successfully unmounted $mountpoint for user $username."
                else
                    log "Failed to unmount $mountpoint for user $username."
                fi
            else
                log "User $username is still logged in. Skipping unmount."
            fi
        fi
    done < <(mount | awk '$5 ~ /^nfs/ {print $1, $3, $5, $6}')
}

# ---------------------------------------------------------------------------
# Heartbeat
#
# One heartbeat per timer run tells the broker what this host looks like: agent and script
# versions, OS, desktop, xrdp, NFS, load, memory, disk and sessions. The portal's fleet health
# reports on it, and nothing is decided from it, so every failure here is logged and ignored:
# reconciliation must never depend on it.
# ---------------------------------------------------------------------------

HEARTBEAT_SCRIPTS=(release-session.sh logind-session-watcher.sh xrdp-who-xorg.sh create-user.sh manage-lease.sh apply-host-settings.sh session-control.sh patch-host.sh)
HEARTBEAT_BACKOFF_SECONDS=900

# The version an installed script declares, so a host that was only partly migrated shows up.
script_version() {
    local path="$1"
    local version

    [ -r "$path" ] || return 1
    version=$(grep -m1 -E '^LINUXBROKER_AGENT_VERSION="[^"]+"$' "$path" 2>/dev/null | cut -d'"' -f2)
    [ -n "$version" ] || return 1
    echo "$version"
}

collect_script_versions() {
    local name
    local version
    local versions='{}'

    for name in "${HEARTBEAT_SCRIPTS[@]}"; do
        [ -e "$LOCATION_PATH/$name" ] || continue

        # A script that predates the version constant is reported as null.
        if version=$(script_version "$LOCATION_PATH/$name"); then
            versions=$(/usr/bin/jq -c --arg name "$name" --arg version "$version" '. + {($name): $version}' <<< "$versions")
        else
            versions=$(/usr/bin/jq -c --arg name "$name" '. + {($name): null}' <<< "$versions")
        fi
    done

    echo "$versions"
}

detect_desktop() {
    if command -v gnome-shell >/dev/null 2>&1; then
        echo "gnome"
    elif command -v xfce4-session >/dev/null 2>&1; then
        echo "xfce"
    elif command -v mate-session >/dev/null 2>&1; then
        echo "mate"
    elif command -v startplasma-x11 >/dev/null 2>&1; then
        echo "kde"
    else
        echo "none"
    fi
}

detect_xrdp_version() {
    local line

    command -v xrdp >/dev/null 2>&1 || return 1
    line=$(xrdp --version 2>/dev/null | head -n 1)
    [[ "$line" =~ ([0-9]+(\.[0-9]+)+) ]] || return 1
    echo "${BASH_REMATCH[1]}"
}

# Prints "<mounted homes> <true|false|null>". Mounted NFS homes are checked with a bounded
# stat, because a hung share blocks forever. With none mounted, a TCP connection to the NFS
# server remembered from an earlier mount shows whether a new checkout could mount one.
check_nfs() {
    local server_file="$STATE_DIRECTORY/nfs_server"
    local mounts=0
    local reachable="null"
    local server=""
    local source
    local mountpoint

    while read -r source mountpoint; do
        [ -z "$mountpoint" ] && continue
        mounts=$((mounts + 1))
        [ -z "$server" ] && server="${source%%:*}"

        if timeout 5 stat -f "$mountpoint" >/dev/null 2>&1; then
            [ "$reachable" = "null" ] && reachable="true"
        else
            reachable="false"
        fi
    done < <(awk '$3 ~ /^nfs/ && $2 ~ /^\/home\/[^\/]+$/ {print $1, $2}' /proc/mounts 2>/dev/null)

    if [ "$mounts" -gt 0 ]; then
        if [[ "$server" =~ ^[A-Za-z0-9._-]+$ ]]; then
            printf '%s\n' "$server" > "$server_file" 2>/dev/null && chmod 600 "$server_file" 2>/dev/null
        fi
    elif [ -s "$server_file" ]; then
        server=$(head -n 1 "$server_file" 2>/dev/null)
        if [[ "$server" =~ ^[A-Za-z0-9._-]+$ ]]; then
            if timeout 5 bash -c "exec 3<>/dev/tcp/$server/2049" 2>/dev/null; then
                reachable="true"
            else
                reachable="false"
            fi
        fi
    fi

    echo "$mounts $reachable"
}

# One entry of the heartbeat's session list, from what the reconcile run already knows.
session_json() {
    local username="$1"
    local state="$2"
    local start_time="$3"
    local active_pid="$4"
    local started=""
    local disconnected_since
    local idle=""

    if [ -n "$start_time" ]; then
        started=$(date -d "$start_time" +%s 2>/dev/null || true)
    fi

    disconnected_since=$(get_disconnect_timestamp "$username")

    if [ "$state" = "active" ] && [ -n "$active_pid" ]; then
        idle=$(get_session_idle_seconds "$active_pid" 2>/dev/null || true)
    fi

    /usr/bin/jq -cn \
        --arg username "$username" \
        --arg state "$state" \
        --arg started "$started" \
        --arg disconnectedSince "$disconnected_since" \
        --arg idle "$idle" \
        'def num: if . == "" then null else (tonumber? // null) end;
         {username: $username, state: $state, sessionStart: ($started | num),
          disconnectedSince: ($disconnectedSince | num), idleSeconds: ($idle | num)}'
}

build_heartbeat() {
    local sessions_json="${1:-[]}"
    local os_id=""
    local os_version=""
    local os_name=""
    local xrdp_version
    local xrdp_active="false"
    local nfs_mounts
    local nfs_reachable
    local disk_used

    if [ -r /etc/os-release ]; then
        os_id=$(. /etc/os-release && echo "${ID:-}")
        os_version=$(. /etc/os-release && echo "${VERSION_ID:-}")
        os_name=$(. /etc/os-release && echo "${PRETTY_NAME:-}")
    fi

    xrdp_version=$(detect_xrdp_version || true)
    if systemctl is-active --quiet xrdp 2>/dev/null; then
        xrdp_active="true"
    fi

    read -r nfs_mounts nfs_reachable < <(check_nfs)
    disk_used=$(df -P / 2>/dev/null | awk 'NR == 2 {gsub("%", "", $5); print $5}')

    /usr/bin/jq -cn \
        --arg agentVersion "$LINUXBROKER_AGENT_VERSION" \
        --argjson scriptVersions "$(collect_script_versions)" \
        --arg settingsVersion "$SETTINGS_VERSION" \
        --arg osId "$os_id" \
        --arg osVersion "$os_version" \
        --arg osName "$os_name" \
        --arg kernel "$(uname -r 2>/dev/null)" \
        --arg desktop "$(detect_desktop)" \
        --arg xrdpVersion "$xrdp_version" \
        --argjson xrdpActive "$xrdp_active" \
        --arg nfsMounts "$nfs_mounts" \
        --arg nfsReachable "$nfs_reachable" \
        --arg load "$(awk '{print $1}' /proc/loadavg 2>/dev/null)" \
        --arg cpuCount "$(nproc 2>/dev/null)" \
        --arg memoryAvailableMb "$(awk '/^MemAvailable:/ {print int($2 / 1024)}' /proc/meminfo 2>/dev/null)" \
        --arg memoryTotalMb "$(awk '/^MemTotal:/ {print int($2 / 1024)}' /proc/meminfo 2>/dev/null)" \
        --arg diskUsed "$disk_used" \
        --arg uptime "$(awk '{print int($1)}' /proc/uptime 2>/dev/null)" \
        --argjson sessions "$sessions_json" \
        'def num: if . == "" then null else (tonumber? // null) end;
         def text: if . == "" then null else . end;
         {
           agentVersion: $agentVersion,
           scriptVersions: $scriptVersions,
           settingsVersion: ($settingsVersion | num),
           os: {id: ($osId | text), version: ($osVersion | text), name: ($osName | text)},
           kernel: ($kernel | text),
           desktop: $desktop,
           xrdp: {version: ($xrdpVersion | text), active: $xrdpActive},
           nfs: {
             mounts: ($nfsMounts | num),
             reachable: (if $nfsReachable == "true" then true elif $nfsReachable == "false" then false else null end)
           },
           loadAverage: ($load | num),
           cpuCount: ($cpuCount | num),
           memoryAvailableMb: ($memoryAvailableMb | num),
           memoryTotalMb: ($memoryTotalMb | num),
           rootDiskFreePct: (($diskUsed | num) as $used | if $used == null then null else 100 - $used end),
           uptimeSeconds: ($uptime | num),
           sessions: $sessions
         }'
}

# Whether this run sends a heartbeat. Watcher runs are extra reconciles triggered by sign-ins
# and sign-outs; the timer run reports on a steady schedule. A broker that answered 404 is
# asked again only once the backoff has passed.
heartbeat_due() {
    local backoff_file="$STATE_DIRECTORY/heartbeat_unsupported_until"
    local backoff_until

    if [ "$RUN_MODE" = "logind-watcher" ]; then
        return 1
    fi

    if [ -s "$backoff_file" ]; then
        backoff_until=$(tr -dc '0-9' < "$backoff_file")
        if [ -n "$backoff_until" ] && [ "$(date +%s)" -lt "$backoff_until" ]; then
            return 1
        fi
    fi

    return 0
}

send_heartbeat() {
    local sessions_json="${1:-[]}"
    local api_base_url="YOUR_LINUX_BROKER_API_BASE_URL"
    local heartbeat_url="$api_base_url/hosts/$hostname/heartbeat"
    local backoff_file="$STATE_DIRECTORY/heartbeat_unsupported_until"
    local failed_file="$STATE_DIRECTORY/heartbeat_failed"
    local payload_file
    local access_token
    local http_status
    local now

    if ! heartbeat_due; then
        return 0
    fi

    now=$(date +%s)

    if ! access_token=$(get_access_token); then
        log "Unable to obtain an access token for the heartbeat."
        return 0
    fi

    payload_file="$STATE_DIRECTORY/heartbeat.$$.json"
    if ! build_heartbeat "$sessions_json" > "$payload_file" 2>/dev/null; then
        log "Could not build the heartbeat."
        rm -f "$payload_file"
        return 0
    fi

    http_status=$(/usr/bin/curl -s -m 10 -w "%{http_code}" -o /dev/null -X POST "$heartbeat_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json" \
        --data-binary "@$payload_file")
    rm -f "$payload_file"

    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        rm -f "$backoff_file"
        if [ -e "$failed_file" ]; then
            rm -f "$failed_file"
            log "The broker is accepting heartbeats again."
        fi
        return 0
    fi

    if [ "$http_status" = "404" ]; then
        # An API older than heartbeats, or a host the broker does not know. Neither changes
        # within a minute, so ask again later instead of on every run.
        printf '%s\n' "$((now + HEARTBEAT_BACKOFF_SECONDS))" > "$backoff_file"
        chmod 600 "$backoff_file"
        log "The broker does not accept heartbeats from $hostname (HTTP 404). Trying again in $((HEARTBEAT_BACKOFF_SECONDS / 60)) minutes."
        return 0
    fi

    # Logged once per outage rather than on every run.
    if [ ! -e "$failed_file" ]; then
        : > "$failed_file"
        chmod 600 "$failed_file"
        log "Heartbeat failed (HTTP $http_status). It is retried on every run."
    fi
}

main() {
    local session_info_script
    local now
    local line
    local pid
    local username
    local start_time
    local status
    local disconnected_at
    local prev_user
    local active_pid
    local start_clock
    local sessions_json='[]'
    local current_users=()
    local previous_users=()
    declare -A user_status=()
    declare -A user_active_pids=()
    declare -A user_start_times=()

    ensure_state_files
    load_settings
    refresh_settings

    if ! session_info_script=$(resolve_xrdp_users_info_script); then
        log "ERROR: Failed to find an XRDP session inspection script."
        exit 1
    fi

    if ! "$session_info_script" > "$CURRENT_USERS_DETAILS"; then
        log "ERROR: Failed to execute $session_info_script"
        exit 1
    fi

    log "Contents of $CURRENT_USERS_DETAILS:"
    cat "$CURRENT_USERS_DETAILS" | tee -a "$LOG_FILE"

    mapfile -t previous_users < "$PREVIOUS_USERS_FILE"
    now=$(date +%s)

    while IFS= read -r line; do
        [ -z "$line" ] && continue

        pid=$(echo "$line" | awk '{print $1}')
        username=$(echo "$line" | awk '{print $2}')
        start_time=$(echo "$line" | awk '{print $3}')
        start_clock=$(echo "$line" | awk '{print $4}')
        status=$(echo "$line" | awk '{print $NF}' | sed -E 's/\x1B\[[0-9;]*[[:alpha:]]//g' | xargs)

        if [ -z "$username" ] || [ "$pid" = "PID" ]; then
            continue
        fi

        if ! array_contains "$username" "${current_users[@]}"; then
            current_users+=("$username")
        fi

        if [ -z "${user_start_times[$username]:-}" ] && [[ "$start_time" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            user_start_times["$username"]="$start_time $start_clock"
        fi

        if ! [[ -z "$start_time" || "$start_time" == *"START_TIME"* ]]; then
            log "PID: $pid, Username: $username, Start Time: $start_time, Status: $status"
        fi

        if [[ "$status" == *"active"* ]]; then
            user_status["$username"]="active"
            user_active_pids["$username"]+="$pid "
        elif [[ "$status" == *"disconnected"* ]]; then
            if [ "${user_status[$username]:-}" != "active" ]; then
                user_status["$username"]="disconnected"
            fi
        else
            log "User $username reported unexpected session status '$status'."
        fi
    done < "$CURRENT_USERS_DETAILS"

    for username in "${current_users[@]}"; do
        disconnected_at=$(get_disconnect_timestamp "$username")

        if [ "${user_status[$username]:-}" = "active" ]; then
            if [ -n "$disconnected_at" ]; then
                log "User $username reconnected. Clearing pending grace period."
                clear_disconnect_timestamp "$username"
            else
                log "User $username is active. No action to perform."
            fi

            for active_pid in ${user_active_pids[$username]:-}; do
                enforce_idle_session "$username" "$active_pid"
            done
        elif [ "${user_status[$username]:-}" = "disconnected" ]; then
            if [ -z "$disconnected_at" ]; then
                log "User $username is disconnected. Releasing VM and starting grace period."

                if release_vm "$username"; then
                    upsert_disconnect_timestamp "$username" "$now"
                else
                    log "ERROR: Release request failed for user $username. The agent will retry on the next run."
                fi
            else
                reconcile_disconnected_user "$username" "$disconnected_at" "$now"
            fi
        fi
    done

    for prev_user in "${previous_users[@]}"; do
        [ -z "$prev_user" ] && continue

        if ! array_contains "$prev_user" "${current_users[@]}"; then
            log "User $prev_user has no session record. Releasing VM for user $prev_user."
            release_vm "$prev_user" || true
            clear_disconnect_timestamp "$prev_user"
            tsv_clear "$IDLE_WARNED_USERS_FILE" "$prev_user"
        fi
    done

    if [ "${#current_users[@]}" -gt 0 ]; then
        printf "%s\n" "${current_users[@]}" > "$PREVIOUS_USERS_FILE"
    else
        : > "$PREVIOUS_USERS_FILE"
    fi

    chmod 600 "$PREVIOUS_USERS_FILE"

    check_unmount_user_homes

    # The session list reads each active session's idle time from its X server, so it is
    # only built on a run that sends it.
    if heartbeat_due; then
        for username in "${current_users[@]}"; do
            active_pid="${user_active_pids[$username]:-}"
            active_pid="${active_pid%% *}"
            sessions_json=$(/usr/bin/jq -c --argjson entry "$(session_json "$username" "${user_status[$username]:-unknown}" "${user_start_times[$username]:-}" "$active_pid")" '. + [$entry]' <<< "$sessions_json" 2>/dev/null || echo "$sessions_json")
        done

        send_heartbeat "$sessions_json" || true
    fi

    log "Script completed."
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    acquire_reconcile_lock
    log "Script started."
    trap "release_reconcile_lock; log 'Script exiting.'" EXIT INT TERM

    main
fi

