#!/bin/bash

# Support for RHEL systems

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

LOG_FILE="/var/log/release-session.log"
LOCATION_PATH="/usr/local/bin"
XORG_USERS_INFO_SCRIPT="$LOCATION_PATH/xrdp-who-xorg.sh"
APPLY_SETTINGS_SCRIPT="$LOCATION_PATH/apply-host-settings.sh"
SETTINGS_FILE="/etc/linuxbroker/host-settings.conf"
STATE_DIRECTORY="/var/lib/linuxbroker-release-session"
LEASE_DIRECTORY="$STATE_DIRECTORY/leases"
CURRENT_USERS_DETAILS="$STATE_DIRECTORY/current_users.txt"
PREVIOUS_USERS_FILE="$STATE_DIRECTORY/previous_users.txt"
DISCONNECTED_USERS_FILE="$STATE_DIRECTORY/disconnected_users.tsv"
IDLE_WARNED_USERS_FILE="$STATE_DIRECTORY/idle_warned_users.tsv"
ACKED_VERSION_FILE="$STATE_DIRECTORY/acked_settings_version"
LOCK_FILE="$STATE_DIRECTORY/reconcile.lock"
hostname=$(hostname)
LOCK_FD=""

# Defaults matching the seeded profile in
# sql_queries/028_create_table-linux_host_settings.sql. They apply only until the first
# successful settings fetch, so a host that has never reached the broker behaves exactly as
# it did before these settings became configurable.
GRACE_PERIOD_SECONDS=1200
IDLE_TIMEOUT_SECONDS=0
IDLE_WARNING_SECONDS=120
SETTINGS_VERSION=0

RUN_MODE="manual"

for arg in "$@"; do
    case "$arg" in
        --systemd-timer)
            RUN_MODE="systemd-timer"
            ;;
        --logind-watcher)
            RUN_MODE="logind-watcher"
            ;;
        --cron)
            RUN_MODE="cron"
            ;;
    esac
done

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - [$RUN_MODE] - $1" | tee -a "$LOG_FILE"
}

ensure_state_files() {
    mkdir -p "$STATE_DIRECTORY"
    touch "$LOG_FILE" "$CURRENT_USERS_DETAILS" "$PREVIOUS_USERS_FILE" "$DISCONNECTED_USERS_FILE" "$IDLE_WARNED_USERS_FILE"
    chmod 600 "$LOG_FILE" "$CURRENT_USERS_DETAILS" "$PREVIOUS_USERS_FILE" "$DISCONNECTED_USERS_FILE" "$IDLE_WARNED_USERS_FILE"
}

acquire_reconcile_lock() {
    mkdir -p "$STATE_DIRECTORY"
    exec {LOCK_FD}> "$LOCK_FILE"

    if ! flock -n "$LOCK_FD"; then
        log "Another reconciliation run is already in progress. Skipping this invocation."
        eval "exec ${LOCK_FD}>&-"
        LOCK_FD=""
        exit 0
    fi
}

release_reconcile_lock() {
    if [ -n "$LOCK_FD" ]; then
        flock -u "$LOCK_FD" 2>/dev/null || true
        eval "exec ${LOCK_FD}>&-"
        LOCK_FD=""
    fi
}

resolve_xrdp_users_info_script() {
    if [ -x "$XORG_USERS_INFO_SCRIPT" ]; then
        echo "$XORG_USERS_INFO_SCRIPT"
        return 0
    fi

    return 1
}

array_contains() {
    local needle="$1"
    shift
    local item

    for item in "$@"; do
        if [ "$item" = "$needle" ]; then
            return 0
        fi
    done

    return 1
}

get_disconnect_timestamp() {
    tsv_get "$DISCONNECTED_USERS_FILE" "$1"
}

upsert_disconnect_timestamp() {
    tsv_upsert "$DISCONNECTED_USERS_FILE" "$1" "$2"
}

clear_disconnect_timestamp() {
    tsv_clear "$DISCONNECTED_USERS_FILE" "$1"
}

# Generic single-key-per-user TSV helpers, shared by the disconnect and idle-warning state
# files so both behave identically.
tsv_get() {
    local file="$1"
    local username="$2"

    [ -f "$file" ] || return 0

    awk -F '\t' -v user="$username" '$1 == user {print $2; exit}' "$file"
}

tsv_upsert() {
    local file="$1"
    local username="$2"
    local value="$3"
    local tmp_file

    touch "$file"
    tmp_file=$(mktemp)
    awk -F '\t' -v user="$username" '$1 != user' "$file" > "$tmp_file"
    printf '%s\t%s\n' "$username" "$value" >> "$tmp_file"
    mv "$tmp_file" "$file"
    chmod 600 "$file"
}

tsv_clear() {
    local file="$1"
    local username="$2"
    local tmp_file

    [ -f "$file" ] || return 0

    tmp_file=$(mktemp)
    awk -F '\t' -v user="$username" '$1 != user' "$file" > "$tmp_file"
    mv "$tmp_file" "$file"
    chmod 600 "$file"
}

# Reads the cached settings profile written by apply-host-settings.sh. The file only ever
# contains integers and booleans generated by that script, so sourcing it is safe.
load_settings() {
    if [ ! -r "$SETTINGS_FILE" ]; then
        return 0
    fi

    . "$SETTINGS_FILE"

    GRACE_PERIOD_SECONDS="${LINUXBROKER_GRACE_PERIOD_SECONDS:-$GRACE_PERIOD_SECONDS}"
    IDLE_TIMEOUT_SECONDS="${LINUXBROKER_IDLE_TIMEOUT_SECONDS:-$IDLE_TIMEOUT_SECONDS}"
    IDLE_WARNING_SECONDS="${LINUXBROKER_IDLE_WARNING_SECONDS:-$IDLE_WARNING_SECONDS}"
    SETTINGS_VERSION="${LINUXBROKER_SETTINGS_VERSION:-$SETTINGS_VERSION}"
}

# Pull side of settings delivery. Every failure path here is non-fatal: reconciliation is
# the job that actually reclaims VMs, so it must never be blocked by a settings problem.
refresh_settings() {
    local api_base_url="YOUR_LINUX_BROKER_API_BASE_URL"
    local settings_url="$api_base_url/hosts/settings"
    local ack_url="$api_base_url/hosts/$hostname/settings/ack"
    local access_token
    local response_file
    local http_status
    local fetched_version

    # Settings are only refreshed from the timer path. A watcher-mode run is a child of the
    # watcher service, and applying settings can restart that unit, which would SIGTERM this
    # process part-way through a reconcile. The timer path applies the change within one
    # interval anyway, so nothing is lost by skipping it here.
    if [ "$RUN_MODE" = "logind-watcher" ]; then
        return 0
    fi

    if [ ! -x "$APPLY_SETTINGS_SCRIPT" ]; then
        log "Settings apply script $APPLY_SETTINGS_SCRIPT is unavailable. Continuing with cached settings."
        return 0
    fi

    if ! access_token=$(get_access_token); then
        log "Unable to obtain an access token for the settings fetch. Continuing with cached settings."
        return 0
    fi

    response_file=$(mktemp)

    http_status=$(/usr/bin/curl -s -m 20 -w "%{http_code}" -o "$response_file" -X GET "$settings_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json")

    if ! [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        log "Settings fetch returned HTTP $http_status. Continuing with cached settings."
        rm -f "$response_file"
        return 0
    fi

    fetched_version=$(/usr/bin/jq -r '.SettingsVersion // empty' "$response_file" 2>/dev/null)

    if ! [[ "$fetched_version" =~ ^[0-9]+$ ]]; then
        log "Settings response did not contain a usable SettingsVersion. Continuing with cached settings."
        rm -f "$response_file"
        return 0
    fi

    if [ "$fetched_version" = "$SETTINGS_VERSION" ]; then
        # Already applied. The acknowledgement is tracked separately because it happens after
        # the version is written to disk; without this retry a single failed ack would leave
        # the host reported as drifted forever even though it is fully converged.
        if [ "$(read_acked_version)" != "$fetched_version" ]; then
            acknowledge_settings "$ack_url" "$access_token" "$fetched_version"
        fi

        rm -f "$response_file"
        return 0
    fi

    log "Applying settings version $fetched_version (was $SETTINGS_VERSION)."

    if "$APPLY_SETTINGS_SCRIPT" < "$response_file" >> "$LOG_FILE" 2>&1; then
        load_settings
        acknowledge_settings "$ack_url" "$access_token" "$fetched_version"
    else
        log "ERROR: Failed to apply settings version $fetched_version. Continuing with cached settings."
    fi

    rm -f "$response_file"
}

read_acked_version() {
    if [ -s "$ACKED_VERSION_FILE" ]; then
        tr -d '\r\n' < "$ACKED_VERSION_FILE"
    fi
}

acknowledge_settings() {
    local ack_url="$1"
    local access_token="$2"
    local applied_version="$3"
    local http_status

    http_status=$(/usr/bin/curl -s -m 20 -w "%{http_code}" -o /dev/null -X POST "$ack_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json" \
        -d "$(/usr/bin/jq -cn --argjson settingsVersion "$applied_version" '{settingsVersion: $settingsVersion}')")

    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        # Recorded only on success, so a failed acknowledgement is retried on the next run.
        printf '%s\n' "$applied_version" > "$ACKED_VERSION_FILE"
        chmod 600 "$ACKED_VERSION_FILE"
        log "Acknowledged settings version $applied_version."
    else
        log "Could not acknowledge settings version $applied_version (HTTP $http_status)."
    fi
}

terminate_session_processes() {
    local username="$1"
    local found_process="false"

    while IFS=: read -r pid process_name; do
        [ -z "$pid" ] && continue

        found_process="true"
        log "$process_name PID for user $username: $pid"

        if kill -9 "$pid" 2>/dev/null; then
            log "Terminated $process_name process $pid for user $username."
        else
            log "ERROR: Failed to terminate $process_name process $pid for user $username."
        fi
    done < <(
        ps h -C Xorg -o pid=,user=,comm= 2>/dev/null | awk -v user="$username" '$2 == user {print $1 ":" $3}'
    )

    if [ "$found_process" != "true" ]; then
        log "No XRDP session process found for user $username."
    fi
}

get_access_token() {
    local resource="api://YOUR_LINUX_BROKER_API_CLIENT_ID"
    local imds_endpoint="http://169.254.169.254/metadata/identity/oauth2/token"
    local api_version="2018-02-01"
    local uri="$imds_endpoint?api-version=$api_version&resource=$resource"

    local headers="Metadata:true"
    local access_token=$(/usr/bin/curl -s -m 10 --header "$headers" "$uri" | /usr/bin/jq -r '.access_token')

    if [ "$access_token" == "null" ] || [ -z "$access_token" ]; then
        log "ERROR: Failed to obtain access token."
        # Returning rather than exiting lets non-critical callers such as the settings fetch
        # continue. release_vm still treats an empty token as fatal.
        return 1
    fi

    echo "$access_token"
}

get_current_lease_id() {
    local username="$1"
    local lease_file="$LEASE_DIRECTORY/$username.lease"

    if [ ! -f "$lease_file" ]; then
        return 1
    fi

    tr -d '\r\n' < "$lease_file"
}

release_vm() {
    local username="$1"
    local api_base_url="YOUR_LINUX_BROKER_API_BASE_URL"
    local release_vm_url="$api_base_url/vms/$hostname/release"
    local access_token
    local lease_id=""
    local request_body
    local response_file
    local http_status
    local json_hostname
    local json_lease_id
    local release_status
    local release_succeeded=1

    access_token=$(get_access_token)

    if [ -z "$access_token" ]; then
        log "ERROR: Unable to obtain access token."
        exit 1
    fi

    if lease_id=$(get_current_lease_id "$username"); then
        request_body=$(/usr/bin/jq -cn --arg username "$username" --arg leaseId "$lease_id" '{username: $username, leaseId: $leaseId}')
    else
        log "No lease marker found for user $username. Falling back to username-only release."
        request_body=$(/usr/bin/jq -cn --arg username "$username" '{username: $username}')
    fi

    response_file=$(mktemp)

    http_status=$(/usr/bin/curl -s -w "%{http_code}" -o "$response_file" -X POST "$release_vm_url" \
        -H "Authorization: Bearer $access_token" \
        -H "Content-Type: application/json" \
        -d "$request_body")

    json_hostname=$(/usr/bin/jq -r '.Hostname // empty' "$response_file" 2>/dev/null)
    json_lease_id=$(/usr/bin/jq -r '.LeaseId // empty' "$response_file" 2>/dev/null)
    release_status=$(/usr/bin/jq -r '.ReleaseStatus // empty' "$response_file" 2>/dev/null)

    if [[ "$http_status" =~ ^2[0-9][0-9]$ ]]; then
        if [ "$release_status" == "NoActiveAssignment" ]; then
            log "INFO: VM $hostname already has no active assignment. Nothing to release for user $username."
            release_succeeded=0
        elif [ "$json_hostname" != "$hostname" ]; then
            log "ERROR: Release response returned Hostname '$json_hostname' but expected '$hostname'."
        elif [ -n "$lease_id" ] && [ "$json_lease_id" != "$lease_id" ]; then
            log "ERROR: Release response for $hostname returned LeaseId '$json_lease_id' but expected '$lease_id'."
        else
            log "INFO: Successfully released VM with Hostname: $hostname"
            release_succeeded=0
        fi
    elif [ "$http_status" == "409" ]; then
        # The broker reassigned this host, so retrying cannot succeed.
        log "INFO: Lease for user $username on $hostname is stale. Skipping further release attempts."
        release_succeeded=0
    elif [ "$http_status" == "404" ]; then
        log "ERROR: The broker does not recognize Hostname $hostname. Skipping further release attempts."
        release_succeeded=0
    else
        log "ERROR: Failed to release VM with Hostname: $hostname (HTTP Status: $http_status)"
    fi

    cat "$response_file" >> "$LOG_FILE"

    terminate_session_processes "$username"

    rm -f "$response_file"

    return "$release_succeeded"
}

terminate_logind_sessions() {
    local username="$1"
    local session_ids
    local session_id

    session_ids=$(loginctl list-sessions --no-legend 2>/dev/null | awk -v user="$username" '$3 == user {print $1}')

    if [ -z "$session_ids" ]; then
        log "No logind sessions found for user $username."
        return 0
    fi

    for session_id in $session_ids; do
        if loginctl terminate-session "$session_id"; then
            log "Logged off user $username session $session_id after grace period."
        else
            log "ERROR: Failed to log off user $username session $session_id."
        fi
    done
}

reconcile_disconnected_user() {
    local username="$1"
    local disconnected_at="$2"
    local now="$3"
    local elapsed=$((now - disconnected_at))
    local remaining

    if [ "$elapsed" -ge "$GRACE_PERIOD_SECONDS" ]; then
        log "User $username remained disconnected for $elapsed seconds. Terminating remaining sessions."
        terminate_logind_sessions "$username"
        clear_disconnect_timestamp "$username"
        return
    fi

    remaining=$((GRACE_PERIOD_SECONDS - elapsed))
    log "User $username is still disconnected. Grace period expires in $remaining seconds."
}

# ---------------------------------------------------------------------------
# Idle session enforcement
#
# Disabled when IDLE_TIMEOUT_SECONDS is 0, which is the shipped default.
#
# Enforcement deliberately fails open. If idle time cannot be read for any reason the user
# is left alone, because wrongly disconnecting an active user is far worse than letting an
# idle one hold a VM for another poll.
# ---------------------------------------------------------------------------

get_session_display() {
    local xorg_pid="$1"

    tr '\0' '\n' < "/proc/$xorg_pid/cmdline" 2>/dev/null | grep -m1 -E '^:[0-9]+$'
}

get_session_xauthority() {
    local xorg_pid="$1"
    local auth_path
    local xorg_cwd

    auth_path=$(tr '\0' '\n' < "/proc/$xorg_pid/cmdline" 2>/dev/null | awk '$0 == "-auth" { getline; print; exit }')

    if [ -z "$auth_path" ]; then
        return 0
    fi

    # xrdp 0.9.x passes a bare ".Xauthority", which is only meaningful relative to the Xorg
    # process's working directory (the session owner's home). This agent runs with its own
    # WorkingDirectory, so the path has to be resolved here or every idle lookup would fail
    # to open the display and idle enforcement would silently never fire.
    if [ "${auth_path#/}" = "$auth_path" ]; then
        xorg_cwd=$(readlink -f "/proc/$xorg_pid/cwd" 2>/dev/null)

        if [ -n "$xorg_cwd" ]; then
            auth_path="$xorg_cwd/$auth_path"
        fi
    fi

    echo "$auth_path"
}

get_session_idle_seconds() {
    local xorg_pid="$1"
    local display
    local xauthority
    local idle_milliseconds

    if ! command -v xprintidle >/dev/null 2>&1; then
        return 1
    fi

    display=$(get_session_display "$xorg_pid")
    if [ -z "$display" ]; then
        return 1
    fi

    xauthority=$(get_session_xauthority "$xorg_pid")

    if [ -n "$xauthority" ]; then
        idle_milliseconds=$(DISPLAY="$display" XAUTHORITY="$xauthority" xprintidle 2>/dev/null)
    else
        idle_milliseconds=$(DISPLAY="$display" xprintidle 2>/dev/null)
    fi

    if ! [[ "$idle_milliseconds" =~ ^[0-9]+$ ]]; then
        return 1
    fi

    echo $((idle_milliseconds / 1000))
}

warn_idle_user() {
    local username="$1"
    local xorg_pid="$2"
    local remaining="$3"
    local display
    local xauthority
    local user_id
    local message="Your session has been idle and will be disconnected in $remaining seconds. Move the mouse or press a key to stay connected."

    display=$(get_session_display "$xorg_pid")
    [ -z "$display" ] && return 1

    xauthority=$(get_session_xauthority "$xorg_pid")
    user_id=$(id -u "$username" 2>/dev/null)

    if command -v notify-send >/dev/null 2>&1 && [ -n "$user_id" ] && command -v runuser >/dev/null 2>&1; then
        if DISPLAY="$display" XAUTHORITY="$xauthority" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
            runuser -u "$username" -- notify-send "Idle session warning" "$message" >/dev/null 2>&1; then
            return 0
        fi
    fi

    if command -v xmessage >/dev/null 2>&1; then
        DISPLAY="$display" XAUTHORITY="$xauthority" xmessage -timeout 30 "$message" >/dev/null 2>&1 &
        return 0
    fi

    return 1
}

# Drops the client connection while leaving Xorg running, so the session survives and the
# user can reconnect inside the grace period. Only processes named xrdp that hold the
# session's display socket are terminated, which is the same signal xrdp-who-xorg.sh uses to
# decide whether a session is connected.
disconnect_session() {
    local username="$1"
    local xorg_pid="$2"
    local display
    local display_number
    local pid
    local process_name
    local disconnected="false"

    display=$(get_session_display "$xorg_pid")
    if [ -z "$display" ]; then
        log "Could not determine the display for user $username. Skipping idle disconnect."
        return 1
    fi

    display_number="${display#:}"

    while read -r pid; do
        [ -z "$pid" ] && continue
        [ "$pid" = "$xorg_pid" ] && continue

        process_name=$(ps -p "$pid" -o comm= 2>/dev/null | xargs)
        if [ "$process_name" != "xrdp" ]; then
            continue
        fi

        if kill -TERM "$pid" 2>/dev/null; then
            disconnected="true"
            log "Disconnected idle xrdp connection $pid for user $username."
        else
            log "ERROR: Failed to disconnect xrdp connection $pid for user $username."
        fi
    done < <(
        ss -xp 2>/dev/null \
            | grep -E "xrdp_display_${display_number}([^0-9]|$)" \
            | grep -oE 'pid=[0-9]+' \
            | cut -d= -f2 \
            | sort -u
    )

    if [ "$disconnected" != "true" ]; then
        log "No xrdp connection process was found for user $username on display $display."
        return 1
    fi

    return 0
}

enforce_idle_session() {
    local username="$1"
    local xorg_pid="$2"
    local idle_seconds
    local warn_threshold
    local already_warned

    if [ "$IDLE_TIMEOUT_SECONDS" -le 0 ]; then
        return 0
    fi

    if ! idle_seconds=$(get_session_idle_seconds "$xorg_pid"); then
        log "Could not read idle time for user $username. Skipping idle enforcement."
        return 0
    fi

    if [ "$idle_seconds" -ge "$IDLE_TIMEOUT_SECONDS" ]; then
        log "User $username has been idle for $idle_seconds seconds. Disconnecting the session."

        if disconnect_session "$username" "$xorg_pid"; then
            tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
        fi

        return 0
    fi

    if [ "$IDLE_WARNING_SECONDS" -le 0 ]; then
        return 0
    fi

    warn_threshold=$((IDLE_TIMEOUT_SECONDS - IDLE_WARNING_SECONDS))

    if [ "$idle_seconds" -lt "$warn_threshold" ]; then
        # The user is active again, so clear the marker and let a fresh warning be sent if
        # they go idle later. Clearing it any earlier would defeat the dedup check below and
        # re-warn on every single run for the whole warning window.
        tsv_clear "$IDLE_WARNED_USERS_FILE" "$username"
        return 0
    fi

    already_warned=$(tsv_get "$IDLE_WARNED_USERS_FILE" "$username")
    if [ -n "$already_warned" ]; then
        return 0
    fi

    if warn_idle_user "$username" "$xorg_pid" "$((IDLE_TIMEOUT_SECONDS - idle_seconds))"; then
        tsv_upsert "$IDLE_WARNED_USERS_FILE" "$username" "$(date +%s)"
        log "Warned user $username that the session is approaching the idle limit."
    fi
}

check_unmount_user_homes() {
    local username

    log "Scanning for orphaned mounted user home directories."

    mapfile -t logged_in_users < <(loginctl list-users --no-legend 2>/dev/null | awk '{print $2}')

    while read -r device mountpoint fstype rest; do
        if [[ "$mountpoint" =~ ^/home/[^/]+$ ]]; then
            username=$(basename "$mountpoint")

            if ! array_contains "$username" "${logged_in_users[@]}"; then
                log "User $username is not logged in. Attempting to unmount $mountpoint"

                if umount -l "$mountpoint"; then
                    log "Successfully unmounted $mountpoint for user $username."
                else
                    log "Failed to unmount $mountpoint for user $username."
                fi
            else
                log "User $username is still logged in. Skipping unmount."
            fi
        fi
    done < <(mount | awk '$5 ~ /^nfs/ {print $1, $3, $5, $6}')
}

main() {
    local session_info_script
    local now
    local line
    local pid
    local username
    local start_time
    local status
    local disconnected_at
    local prev_user
    local current_users=()
    local previous_users=()

    ensure_state_files
    load_settings
    refresh_settings

    if ! session_info_script=$(resolve_xrdp_users_info_script); then
        log "ERROR: Failed to find an XRDP session inspection script."
        exit 1
    fi

    if ! "$session_info_script" > "$CURRENT_USERS_DETAILS"; then
        log "ERROR: Failed to execute $session_info_script"
        exit 1
    fi

    log "Contents of $CURRENT_USERS_DETAILS:"
    cat "$CURRENT_USERS_DETAILS" | tee -a "$LOG_FILE"

    mapfile -t previous_users < "$PREVIOUS_USERS_FILE"
    now=$(date +%s)

    while IFS= read -r line; do
        [ -z "$line" ] && continue

        pid=$(echo "$line" | awk '{print $1}')
        username=$(echo "$line" | awk '{print $2}')
        start_time=$(echo "$line" | awk '{print $3}')
        status=$(echo "$line" | awk '{print $NF}' | xargs)

        if [ -z "$username" ] || [ "$pid" = "PID" ]; then
            continue
        fi

        current_users+=("$username")

        if ! [[ -z "$start_time" || "$start_time" == *"START_TIME"* ]]; then
            log "PID: $pid, Username: $username, Start Time: $start_time, Status: $status"
        fi

        disconnected_at=$(get_disconnect_timestamp "$username")

        if [[ "$status" == *"active"* ]]; then
            if [ -n "$disconnected_at" ]; then
                log "User $username reconnected. Clearing pending grace period."
                clear_disconnect_timestamp "$username"
            else
                log "User $username is active. No action to perform."
            fi

            enforce_idle_session "$username" "$pid"
        elif [[ "$status" == *"disconnected"* ]]; then
            if [ -z "$disconnected_at" ]; then
                log "User $username is disconnected. Releasing VM and starting grace period."

                if release_vm "$username"; then
                    upsert_disconnect_timestamp "$username" "$now"
                else
                    log "ERROR: Release request failed for user $username. The agent will retry on the next run."
                fi
            else
                reconcile_disconnected_user "$username" "$disconnected_at" "$now"
            fi
        else
            log "User $username reported unexpected session status '$status'."
        fi
    done < "$CURRENT_USERS_DETAILS"

    for prev_user in "${previous_users[@]}"; do
        [ -z "$prev_user" ] && continue

        if ! array_contains "$prev_user" "${current_users[@]}"; then
            log "User $prev_user has no session record. Releasing VM for user $prev_user."
            release_vm "$prev_user" || true
            clear_disconnect_timestamp "$prev_user"
            tsv_clear "$IDLE_WARNED_USERS_FILE" "$prev_user"
        fi
    done

    if [ "${#current_users[@]}" -gt 0 ]; then
        printf "%s\n" "${current_users[@]}" > "$PREVIOUS_USERS_FILE"
    else
        : > "$PREVIOUS_USERS_FILE"
    fi

    chmod 600 "$PREVIOUS_USERS_FILE"

    check_unmount_user_homes

    log "Script completed."
}

acquire_reconcile_lock
log "Script started."
trap "release_reconcile_lock; log 'Script exiting.'" EXIT INT TERM

main

